[tool.poetry]
name = "chatbot-confidential"
version = "0.0.1"
description = "fully-contained (no external API calls) knowledgebase chatbot"
authors = ["Brad Ito <phlogisticfugu@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sanic = {version = "^23.6.0", extras = ["ext"]}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
flake8 = "^6.1.0"
flake8-black = "^0.3.6"
black = "^23.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
