"""permit null vectors in embeddings

Revision ID: 3c2e52612613
Revises: e2d33755acdc
Create Date: 2023-11-02 08:04:21.226222

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.types import NullType


# revision identifiers, used by Alembic.
revision: str = "3c2e52612613"
down_revision: Union[str, None] = "e2d33755acdc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("embedded_chunk", "vector", existing_type=NullType(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "embedded_chunk", "vector", existing_type=NullType(), nullable=False
    )
    # ### end Alembic commands ###
